" Minimal vimrc for git commits and quick edits
set nocompatible

" Display
set number
syntax on
set scrolloff=3

" Tabs and spaces
set tabstop=2
set shiftwidth=2
set expandtab
set smartindent

" Search
set ignorecase
set smartcase
set incsearch
set hlsearch

" No swap/backup files
set nobackup
set noswapfile

" Git commit specific settings
autocmd Filetype gitcommit setlocal spell tw=72 colorcolumn=72
